
# █▀▄▀█ █▀█ █▄░█ █ ▀█▀ █▀█ █▀█ █▀
# █░▀░█ █▄█ █░▀█ █ ░█░ █▄█ █▀▄ ▄█

# Set your monitor configuration here
# See https://wiki.hyprland.org/Configuring/Monitors/
# For a sample file, please refer to https://github.com/prasanthrangan/hyprdots/blob/main/Configs/.config/hypr/monitors.t2

monitor = eDP-1,1920x1080@144,0x0,1.333
monitor = DP-2,1920x1080@165,0x0,1
monitor = DP-1,1920x1080@144,-1920x0,1

workspace = 1,  monitor:DP-2, default:true
workspace = 2,  monitor:DP-2, default:true
workspace = 6,  monitor:DP-2, default:true
workspace = 7,  monitor:DP-2, default:true
workspace = 8,  monitor:DP-2, default:true
workspace = 9,  monitor:DP-2, default:true

workspace = 3,  monitor:DP-1, default:true
workspace = 4,  monitor:DP-1, default:true
workspace = 5,  monitor:DP-1, default:true
