
# █░█ █▀ █▀▀ █▀█   █▀█ █▀█ █▀▀ █▀▀ █▀
# █▄█ ▄█ ██▄ █▀▄   █▀▀ █▀▄ ██▄ █▀░ ▄█

# Set your personal hyprland configuration here
# See https://wiki.hyprland.org/Configuring for more information

# // █ █▄░█ █▀█ █░█ ▀█▀
# // █ █░▀█ █▀▀ █▄█ ░█░


#  Uncomment to enable // change to a preferred value
# 🔗 See https://wiki.hyprland.org/Configuring/Variables/#input
input {
    kb_layout = se
    # follow_mouse = 1
    # sensitivity = 0
    # force_no_accel = 0
    # accel_profile = flat 
    # numlock_by_default = true
    
    repeat_rate   = 30
    repeat_delay  = 300 
    sensitivity = 0.5

    # 🔗 See https://wiki.hyprland.org/Configuring/Variables/#touchpad
    touchpad {
        natural_scroll = yes
    }

}

# 🔗 See https://wiki .hyprland.org/Configuring/Variables/#gestures
gestures {
      workspace_swipe = false
#     workspace_swipe_fingers = 3
}

general {
    gaps_in = 2
    gaps_out = 3
    border_size = 1
    col.active_border = rgba(e9114fff) rgba(990c34ff) 45deg
    layout = dwindle
    resize_on_border = true
}

decoration {
    rounding = 5

    blur {
        enabled = yes
        size = 10
        passes = 3
        new_optimizations = on
        ignore_opacity = on
        xray = false
    }
}

layerrule = blur, waybar
