$HOME/.config/hypr/themes/theme.conf|> $HOME/.config/hypr/themes/colors.conf

$GTK_THEME=Kripton
$ICON_THEME=candy-icons
$CURSOR_THEME=Bibata-Modern-Classic
$CURSOR_SIZE=16
$COLOR_SCHEME=prefer-dark

exec = gsettings set org.gnome.desktop.interface icon-theme '$ICON_THEME'
exec = gsettings set org.gnome.desktop.interface gtk-theme '$GTK_THEME'
exec = gsettings set org.gnome.desktop.interface color-scheme '$COLOR_SCHEME'

general {
    gaps_in = 2
    gaps_out = 3
    border_size = 1
    col.active_border = rgba(e9114fff) rgba(990c34ff) 45deg
    col.inactive_border = rgba(7, 15, 42, 0.58)
    layout = dwindle
    resize_on_border = true
}

decoration {
    rounding = 5
    drop_shadow = false

    blur {
        enabled = yes
        size = 10
        passes = 3
        new_optimizations = on
        ignore_opacity = on
        xray = false
    }
}

layerrule = blur, waybar
